-- Jalankan sekali melalui Supabase SQL Editor.
-- Aplikasi demo menggunakan role anon; kebijakan di bawah mengizinkan operasi CRUD.
-- Untuk deployment publik, batasi akses dengan autentikasi dan RLS yang sesuai.

create table if not exists public.pelanggan (
  id_pelanggan bigint generated by default as identity primary key,
  nama text not null check (length(trim(nama)) > 0),
  no_hp text not null,
  alamat text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.alat_musik (
  id_alat bigint generated by default as identity primary key,
  nama_alat text not null check (length(trim(nama_alat)) > 0),
  harga_sewa_per_hari numeric(14,2) not null check (harga_sewa_per_hari >= 0),
  denda_per_hari numeric(14,2) not null check (denda_per_hari >= 0),
  status text not null default 'Tersedia' check (status in ('Tersedia', 'Disewa')),
  created_at timestamptz not null default now()
);

create table if not exists public.penyewaan (
  id_sewa bigint generated by default as identity primary key,
  id_pelanggan bigint not null references public.pelanggan(id_pelanggan) on delete restrict,
  tgl_sewa date not null,
  tgl_rencana_kembali date not null,
  total_biaya numeric(14,2) not null default 0 check (total_biaya >= 0),
  status_sewa text not null default 'Berlangsung' check (status_sewa in ('Berlangsung', 'Selesai')),
  created_at timestamptz not null default now(),
  check (tgl_rencana_kembali >= tgl_sewa)
);

create table if not exists public.detail_penyewaan (
  id_detail bigint generated by default as identity primary key,
  id_sewa bigint not null references public.penyewaan(id_sewa) on delete cascade,
  id_alat bigint not null references public.alat_musik(id_alat) on delete restrict,
  jumlah integer not null default 1 check (jumlah > 0),
  subtotal numeric(14,2) not null check (subtotal >= 0),
  unique (id_sewa, id_alat)
);

create table if not exists public.pengembalian (
  id_pengembalian bigint generated by default as identity primary key,
  id_sewa bigint not null unique references public.penyewaan(id_sewa) on delete restrict,
  tgl_kembali_aktual date not null,
  hari_terlambat integer not null default 0 check (hari_terlambat >= 0),
  total_denda numeric(14,2) not null default 0 check (total_denda >= 0),
  status_pembayaran_denda text not null default 'Belum Lunas'
    check (status_pembayaran_denda in ('Belum Lunas', 'Sebagian', 'Lunas')),
  created_at timestamptz not null default now()
);

create table if not exists public.pembayaran_denda (
  id_pembayaran bigint generated by default as identity primary key,
  id_pengembalian bigint not null references public.pengembalian(id_pengembalian) on delete restrict,
  tgl_bayar date not null default current_date,
  jumlah_bayar numeric(14,2) not null check (jumlah_bayar > 0),
  metode_bayar text not null check (metode_bayar in ('Tunai', 'Transfer', 'QRIS')),
  created_at timestamptz not null default now()
);

create table if not exists public.jurnal_akuntansi (
  id_jurnal bigint generated by default as identity primary key,
  id_pengembalian bigint not null references public.pengembalian(id_pengembalian) on delete restrict,
  tgl_jurnal date not null default current_date,
  kode_akun text not null,
  nama_akun text not null,
  debit numeric(14,2) not null default 0 check (debit >= 0),
  kredit numeric(14,2) not null default 0 check (kredit >= 0),
  keterangan text not null default '',
  created_at timestamptz not null default now(),
  check ((debit > 0 and kredit = 0) or (kredit > 0 and debit = 0))
);

create index if not exists idx_penyewaan_status_tanggal
  on public.penyewaan(status_sewa, tgl_rencana_kembali);
create index if not exists idx_pengembalian_tanggal
  on public.pengembalian(tgl_kembali_aktual);
create index if not exists idx_jurnal_tanggal
  on public.jurnal_akuntansi(tgl_jurnal desc, id_jurnal desc);
create index if not exists idx_pembayaran_pengembalian
  on public.pembayaran_denda(id_pengembalian);

-- Satu baris alat mewakili satu unit fisik; jumlah per unit pada transaksi adalah 1.
create or replace function public.buat_penyewaan(
  p_id_pelanggan bigint,
  p_tgl_sewa date,
  p_tgl_rencana_kembali date,
  p_items jsonb
) returns bigint
language plpgsql
set search_path = public
as $$
declare
  v_id_sewa bigint;
  v_hari integer;
  v_total numeric(14,2);
  v_jumlah_item integer;
  v_item record;
begin
  if p_tgl_rencana_kembali < p_tgl_sewa then
    raise exception 'Tanggal rencana kembali harus sama atau setelah tanggal sewa';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Pilih minimal satu alat musik';
  end if;

  v_jumlah_item := jsonb_array_length(p_items);
  if (select count(distinct (item.value->>'id_alat')::bigint)
      from jsonb_array_elements(p_items) as item(value)) <> v_jumlah_item then
    raise exception 'Alat yang sama tidak boleh dipilih lebih dari sekali';
  end if;
  if exists (
    select 1 from jsonb_array_elements(p_items) as item(value)
    where coalesce((item.value->>'jumlah')::integer, 1) <> 1
  ) then
    raise exception 'Setiap baris alat mewakili satu unit';
  end if;

  perform a.id_alat
  from public.alat_musik a
  join jsonb_array_elements(p_items) as item(value) on a.id_alat = (item.value->>'id_alat')::bigint
  order by a.id_alat
  for update of a;

  if (select count(*) from public.alat_musik a
      join jsonb_array_elements(p_items) as item(value) on a.id_alat = (item.value->>'id_alat')::bigint
      where a.status = 'Tersedia') <> v_jumlah_item then
    raise exception 'Satu atau lebih alat sudah tidak tersedia';
  end if;

  v_hari := greatest(p_tgl_rencana_kembali - p_tgl_sewa, 1);
  select coalesce(sum(a.harga_sewa_per_hari * v_hari), 0)
    into v_total
    from public.alat_musik a
    join jsonb_array_elements(p_items) as item(value) on a.id_alat = (item.value->>'id_alat')::bigint;

  insert into public.penyewaan (id_pelanggan, tgl_sewa, tgl_rencana_kembali, total_biaya)
  values (p_id_pelanggan, p_tgl_sewa, p_tgl_rencana_kembali, v_total)
  returning id_sewa into v_id_sewa;

  for v_item in
    select a.id_alat, a.harga_sewa_per_hari
    from public.alat_musik a
    join jsonb_array_elements(p_items) as item(value) on a.id_alat = (item.value->>'id_alat')::bigint
  loop
    insert into public.detail_penyewaan (id_sewa, id_alat, jumlah, subtotal)
    values (v_id_sewa, v_item.id_alat, 1, v_item.harga_sewa_per_hari * v_hari);
    update public.alat_musik set status = 'Disewa' where id_alat = v_item.id_alat;
  end loop;

  return v_id_sewa;
end;
$$;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table
  public.pelanggan,
  public.alat_musik,
  public.penyewaan,
  public.detail_penyewaan,
  public.pengembalian,
  public.pembayaran_denda,
  public.jurnal_akuntansi
to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
grant execute on function public.buat_penyewaan(bigint, date, date, jsonb) to anon, authenticated;

-- Saat barang dikembalikan, hitung denda dari detail alat dan akrual jurnal.
create or replace function public.proses_pengembalian()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_rencana date;
  v_tgl_sewa date;
  v_status text;
  v_hari integer;
  v_total numeric(14,2);
begin
  select p.tgl_rencana_kembali, p.tgl_sewa, p.status_sewa
    into v_rencana, v_tgl_sewa, v_status
  from public.penyewaan p where p.id_sewa = new.id_sewa;
  if not found then
    raise exception 'Data penyewaan tidak ditemukan';
  end if;
  if v_status <> 'Berlangsung' then
    raise exception 'Penyewaan ini sudah selesai';
  end if;
  if new.tgl_kembali_aktual < v_tgl_sewa then
    raise exception 'Tanggal kembali tidak boleh sebelum tanggal sewa';
  end if;

  v_hari := greatest(new.tgl_kembali_aktual - v_rencana, 0);
  select coalesce(sum(d.jumlah * a.denda_per_hari * v_hari), 0)
    into v_total
    from public.detail_penyewaan d
    join public.alat_musik a on a.id_alat = d.id_alat
    where d.id_sewa = new.id_sewa;

  new.hari_terlambat := v_hari;
  new.total_denda := v_total;
  new.status_pembayaran_denda := case when v_total = 0 then 'Lunas' else 'Belum Lunas' end;
  return new;
end;
$$;

drop trigger if exists trg_hitung_pengembalian on public.pengembalian;
create trigger trg_hitung_pengembalian
before insert on public.pengembalian
for each row execute function public.proses_pengembalian();

create or replace function public.catat_pengembalian()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  update public.penyewaan set status_sewa = 'Selesai' where id_sewa = new.id_sewa;
  update public.alat_musik a set status = 'Tersedia'
  from public.detail_penyewaan d
  where d.id_sewa = new.id_sewa and d.id_alat = a.id_alat;

  if new.total_denda > 0 then
    insert into public.jurnal_akuntansi
      (id_pengembalian, tgl_jurnal, kode_akun, nama_akun, debit, kredit, keterangan)
    values
      (new.id_pengembalian, new.tgl_kembali_aktual, '1130', 'Piutang Denda', new.total_denda, 0,
       'Akrual denda keterlambatan sewa #' || new.id_sewa),
      (new.id_pengembalian, new.tgl_kembali_aktual, '4110', 'Pendapatan Denda Keterlambatan', 0, new.total_denda,
       'Akrual denda keterlambatan sewa #' || new.id_sewa);
  end if;
  return new;
end;
$$;

drop trigger if exists trg_catat_pengembalian on public.pengembalian;
create trigger trg_catat_pengembalian
after insert on public.pengembalian
for each row execute function public.catat_pengembalian();

-- Pembayaran melunasi piutang; jurnal pendapatan sudah dibuat ketika denda diakui.
create or replace function public.validasi_pembayaran_denda()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_total numeric(14,2);
  v_terbayar numeric(14,2);
begin
  select total_denda into v_total
  from public.pengembalian where id_pengembalian = new.id_pengembalian
  for update;
  if not found then
    raise exception 'Data pengembalian tidak ditemukan';
  end if;
  select coalesce(sum(jumlah_bayar), 0) into v_terbayar
  from public.pembayaran_denda where id_pengembalian = new.id_pengembalian;
  if new.jumlah_bayar > v_total - v_terbayar then
    raise exception 'Pembayaran melebihi sisa denda';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_validasi_pembayaran_denda on public.pembayaran_denda;
create trigger trg_validasi_pembayaran_denda
before insert on public.pembayaran_denda
for each row execute function public.validasi_pembayaran_denda();

create or replace function public.catat_pembayaran_denda()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_total numeric(14,2);
  v_terbayar numeric(14,2);
begin
  select total_denda into v_total from public.pengembalian
  where id_pengembalian = new.id_pengembalian;
  select coalesce(sum(jumlah_bayar), 0) into v_terbayar
  from public.pembayaran_denda where id_pengembalian = new.id_pengembalian;

  update public.pengembalian
  set status_pembayaran_denda = case
    when v_terbayar >= v_total then 'Lunas'
    when v_terbayar > 0 then 'Sebagian'
    else 'Belum Lunas'
  end
  where id_pengembalian = new.id_pengembalian;

  insert into public.jurnal_akuntansi
    (id_pengembalian, tgl_jurnal, kode_akun, nama_akun, debit, kredit, keterangan)
  values
    (new.id_pengembalian, new.tgl_bayar, '1110', 'Kas', new.jumlah_bayar, 0,
     'Pembayaran denda #' || new.id_pembayaran || ' (' || new.metode_bayar || ')'),
    (new.id_pengembalian, new.tgl_bayar, '1130', 'Piutang Denda', 0, new.jumlah_bayar,
     'Pelunasan piutang denda #' || new.id_pembayaran);
  return new;
end;
$$;

drop trigger if exists trg_catat_pembayaran_denda on public.pembayaran_denda;
create trigger trg_catat_pembayaran_denda
after insert on public.pembayaran_denda
for each row execute function public.catat_pembayaran_denda();

-- Peralatan awal agar aplikasi bisa langsung dicoba setelah schema dijalankan.
insert into public.alat_musik (nama_alat, harga_sewa_per_hari, denda_per_hari)
select seed.nama_alat, seed.harga_sewa_per_hari, seed.denda_per_hari
from (values
  ('Gitar Akustik', 50000, 15000),
  ('Gitar Elektrik', 85000, 25000),
  ('Keyboard 61 Key', 120000, 35000),
  ('Drum Set', 200000, 50000),
  ('Bass Elektrik', 80000, 25000),
  ('Mikrofon Wireless', 45000, 12000)
) as seed(nama_alat, harga_sewa_per_hari, denda_per_hari)
where not exists (select 1 from public.alat_musik a where a.nama_alat = seed.nama_alat);

-- Aplikasi tanpa login untuk prototipe akademik. Amankan sebelum penggunaan publik.
do $$
declare
  nama_tabel text;
begin
  foreach nama_tabel in array array[
    'pelanggan', 'alat_musik', 'penyewaan', 'detail_penyewaan',
    'pengembalian', 'pembayaran_denda', 'jurnal_akuntansi'
  ] loop
    execute format('alter table public.%I enable row level security', nama_tabel);
    execute format('drop policy if exists %I on public.%I', 'demo_anon_access_' || nama_tabel, nama_tabel);
    execute format(
      'create policy %I on public.%I for all to anon, authenticated using (true) with check (true)',
      'demo_anon_access_' || nama_tabel, nama_tabel
    );
  end loop;
end;
$$;
